### PR TITLE
Fixing a few bugs that prevent the examples from compiling and adding a gitignore file

### PR DESCRIPTION
**Pull request by slowriot**

### CODE REVIEW

**Comment by darrengarvey** [comment]
Thanks for the PR @slowriot. Could you address the minor comment I made above and I'd be happy to merge this.

**Comment by slowriot** [comment]
Hi Darren; no, the comment is correct - the issue is that, as in the original bug report linked in the extended commit message, shutdown_service in asio is private from 1.49 upwards. You had previously removed calls to it, then a later commit partially reversed your fix leaving it broken again for newer versions of boost. My fix conditionally enables shutfown_service only for the versions where it's not private.

**Comment by slowriot** [comment]
Yep, see my reply inline above.

**Comment by darrengarvey** [comment]
Marvellous! Thanks a lot @slowriot. Patches merged.

**Comment by aggsol** [comment]
:+1:

**Pull request merged**
